### ISSUE TITLE
Cannot find module "./../monitor/stats.json"

### ISSUE THREAD

**Issue by clarkdo** [nuxt-community/webpackmonitor-module#2]
Hi @pi0 , when I try this module, there is a exception `app.js:28 Uncaught Error: Cannot find module "./../monitor/stats.json"`

I think the frontend will get data through `getstats` and no need to load file, the error confused me. Did I miss anything or it is a error at bundle app.js building?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/webpackmonitor-module/issues/c3">#c3</a>)</em></sub></div>

**Comment by clarkdo** [comment]
oh, I saw [the code](https://github.com/webpackmonitor/webpackmonitor/blob/master/client/AppDev.jsx#L4), will take a look for further study

**Comment by clarkdo** [comment]
I think `NODE_ENV` should not be `development` when @pi0/webpackmonitor building, so that module will go into [here](https://github.com/webpackmonitor/webpackmonitor/blob/master/client/index.jsx#L20-L25), I'm not clear your customization, so could you please rebuild the package with `production`?

**Comment by clarkdo** [comment]
oh, sorry, my mistake, i missed `NODE_ENV`

**Comment by pi0** [comment]
Thanks dear @clarkdo for the report. I'm not sure what was wrong but rebuilding with `yarn build` and releaed new version and seems working. Please upgrade to `"@nuxtjs/webpackmonitor": "^0.0.3"` and reopen if problem still exists...

**Comment by clarkdo** [comment]
@pi0  It works, thanks.
