### ISSUE TITLE
Using this module in a nuxt build gives a deprecation error

### ISSUE THREAD

**Issue by douira** [nuxt-community/webpackmonitor-module#9]
### Version

[0.1.0](https://github.com/webpackmonitor-module/releases/tag/0.1.0)

### Reproduction link

[https://codesandbox.io/s/vn52njnjql?fontsize=14](https://codesandbox.io/s/vn52njnjql?fontsize=14)

### Steps to reproduce

Run the build script `yarn build` and see the deprecation error.

### What is expected ?

That the error does not appear.

### What is actually happening?

A deprecation error is being thrown in the build.

### Additional comments?

 ERROR  (node:4816) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead    

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/webpackmonitor-module/issues/c5">#c5</a>)</em></sub></div>

**Comment by douira** [comment]
I guess this issue is solved then?

**Comment by pi0** [comment]
Hi @douira no but [webpackmonitor](https://github.com/webpackmonitor/webpackmonitor) itself is unmaintained :( So need to deprecate this module...
